In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from SktWsegRWR_utf8 import *
from utilities import *
import numpy as np
np.set_printoptions(precision=2, suppress= True)
from sentences import *
from DCS import *
np.set_printoptions(precision=5)
from AlgoTestFactory import *

Dataloader Started[Prob]...
Dataloader Finished[Prob]...


In [3]:
import ProbData
from ProbModels import *

In [4]:
goodDict = pickle.load(open('mergedGood_v2.p', 'rb'))
list(goodDict.keys())[0:10]

['149531.p',
 '339164.p',
 '417907.p',
 '246890.p',
 '225223.p',
 '178903.p',
 '103794.p',
 '387247.p',
 '389386.p',
 '138739.p']

In [197]:
i = 1022
for i in range(500):
    if(goodDict[list(goodDict.keys())[i]] == 'C1020'):
        dcsObj = pickleFixLoad('../Text Segmentation/DCS_pick/' + list(goodDict.keys())[i])
        sentenceObj = pickleFixLoad('../TextSegmentation/corrected_10to20/' + list(goodDict.keys())[i])
#         SeeSentence(sentenceObj)
        (chunkDict, wordList, revMap2Chunk, qu, cngList, verbs) = SentencePreprocess(sentenceObj)
        if(len(wordList) < 7):
            print(list(goodDict.keys())[i], len(wordList))

188914.p 5
416810.p 3
418091.p 4
441958.p 5
187416.p 6
177513.p 3
209977.p 6
401397.p 6
293503.p 3
23348.p 2
24173.p 2
421950.p 3
419962.p 1
274646.p 3
18333.p 1
294274.p 1
10965.p 6
435469.p 3
296141.p 6
425717.p 1


In [200]:
f = '296141.p'
dcsObj = pickleFixLoad('../Text Segmentation/DCS_pick/' + f)
sentenceObj = pickleFixLoad('../TextSegmentation/corrected_10to20/' + f)
SeeSentence(sentenceObj)
(chunkDict, wordList, revMap2Chunk, qu, cngList, verbs) = SentencePreprocess(sentenceObj)


vikrIRAnaSca sarveByaH  pARqaveByaH  prayacCati   
Analyzing  vikrIRAnaSca
0 :  vi ['v'] []
2 :  krIRAnas ['krI'] [{'noun': ['nom. sg. m.'], 'verbform': ['"SKTMW71.html#H_krii"'], 'verb': [['ppr. [9] md.']]}]
10 :  ca ['ca'] [{'indeclinable': ['conj.']}]
Analyzing  sarveByaḥ
0 :  sarveByas ['sarva'] [{'noun': ['abl. pl. m.', 'dat. pl. m.', 'abl. pl. n.', 'dat. pl. n.']}]
Analyzing  pARqaveByaḥ
0 :  pARqaveByas ['pARqava'] [{'noun': ['abl. pl. m.', 'dat. pl. m.']}]
Analyzing  prayacCati
0 :  pra ['pra'] []
0 :  pra ['pra'] []
3 :  yacCati ['yam'] [{'verb': ['pr. [1] ac. sg. 3']}]
3 :  yacCati ['yam'] [{'noun': ['loc. sg. n.', 'loc. sg. m.'], 'verbform': ['"SKTMW211.html#H_yam"'], 'verb': [['ppr. [1] ac.']]}]


In [201]:
print(wordList)
print(verbs)

['krI', 'ca', 'sarva', 'pARqava', 'yam', 'yam']
[0, 4, 5]


In [5]:
pb = ProbModels(fullCo_oc_mat = ProbData.fullCo_oc_mat, unigram_counts = ProbData.unigram_counts,
               cng2cngFullMat = ProbData.cng2cngFullMat, cng2index_dict = ProbData.cng2index_dict,
               w2w_samecng_fullmat=ProbData.w2w_samecng_fullmat, samecng_unigram_counts=ProbData.samecng_unigram_counts,
               v2c_fullMat = ProbData.v2c_fullMat)

In [234]:


# print(pb.get_w2w_mat(wordList, False))
# print()
# print(pb.get_w2w_mat(wordList))

# print(pb.get_w2w_samecng_mat(wordList, False))
# print()
# print(pb.get_w2w_samecng_mat(wordList))

# pb.get_v2c_ranking(wordList, cngList, verbs)
print(pb.get_cng2cng_mat(cngList, False))
print(pb.get_cng2cng_mat(cngList))

[[ 0.       0.87024  0.00268  0.00268  0.12441  0.     ]
 [ 0.26454  0.       0.01306  0.01306  0.44481  0.26454]
 [ 0.04805  0.77063  0.       0.       0.13327  0.04805]
 [ 0.04805  0.77063  0.       0.       0.13327  0.04805]
 [ 0.07204  0.84732  0.0043   0.0043   0.       0.07204]
 [ 0.       0.87024  0.00268  0.00268  0.12441  0.     ]]
[[ 0.       0.87018  0.00268  0.00268  0.12441  0.00005]
 [ 0.26454  0.       0.01306  0.01306  0.4448   0.26454]
 [ 0.04807  0.77035  0.       0.00029  0.13322  0.04807]
 [ 0.04807  0.77035  0.00029  0.       0.13322  0.04807]
 [ 0.07205  0.8473   0.0043   0.0043   0.       0.07205]
 [ 0.00005  0.87018  0.00268  0.00268  0.12441  0.     ]]


In [17]:
algo = SktWsegRWR(
    w2w_modelFunc=pb.get_w2w_mat, 
    t2t_modelFunc=pb.get_cng2cng_mat,
    v2c_modelFunc=pb.get_v2c_ranking,
    sameCng_modelFunc = pb.get_w2w_samecng_mat,
    partition=[0.2, 0.3, 0.1, 0.4]
)


In [270]:
           
for fName in list(goodDict.keys())[0:100]:
    folderTag = goodDict[fName]
    #     print(fName)
    dcsObj = pickleFixLoad('../Text Segmentation/DCS_pick/' + fName)
    if folderTag == "C1020" :
        sentenceObj = pickleFixLoad('../TextSegmentation/corrected_10to20/' + fName)
    else:
        sentenceObj = pickleFixLoad('../TextSegmentation/Pickle_Files/' + fName)
    prediction = algo.predict(sentenceObj, dcsObj)
    #     print(prediction)
    if prediction != None:
        print("Accuracy:", Accuracy(prediction, dcsObj))
    else:
        print(fName)

144415.p
Accuracy: 42.857142857142854
ERROR: Zero or one word in sentence...
354565.p
Accuracy: 60.0
Accuracy: 27.272727272727273
Accuracy: 75.0
191125.p
Accuracy: 54.54545454545455
188914.p
Accuracy: 35.714285714285715
Accuracy: 44.44444444444444
Accuracy: 44.44444444444444
129757.p
Accuracy: 33.333333333333336
Accuracy: 40.0
Accuracy: 20.0
Accuracy: 22.22222222222222
112621.p
162485.p
345062.p
Accuracy: 60.0
Accuracy: 33.333333333333336
Accuracy: 28.571428571428573
Accuracy: 12.5
60936.p
153791.p
Accuracy: 72.72727272727273
355013.p
Accuracy: 40.0
Accuracy: 44.44444444444444
Accuracy: 75.0
429184.p
Accuracy: 75.0
Accuracy: 11.11111111111111
78623.p
Accuracy: 77.77777777777777
Accuracy: 75.0
114389.p
Accuracy: 71.42857142857143
Accuracy: 100.0
Accuracy: 66.66666666666667
176325.p
298447.p
Accuracy: 33.333333333333336
Accuracy: 77.77777777777777
Accuracy: 11.11111111111111
Accuracy: 33.333333333333336
Accuracy: 62.5
Accuracy: 50.0
328842.p
Accuracy: 8.333333333333334
Accuracy: 25.0
Acc

In [61]:
algo = SktWsegRWR(
    w2w_modelFunc=pb.get_w2w_mat, 
    t2t_modelFunc=pb.get_cng2cng_mat,
    v2c_modelFunc=pb.get_v2c_ranking,
    sameCng_modelFunc = pb.get_w2w_samecng_mat,
    partition=[0.2, 0.3, 0.1, 0.05]
)


In [64]:
fName = '296141.p'
folderTag = goodDict[fName]
#     print(fName)
dcsObj = pickleFixLoad('../Text Segmentation/DCS_pick/' + fName)
if folderTag == "C1020" :
    sentenceObj = pickleFixLoad('../TextSegmentation/corrected_10to20/' + fName)
else:
    sentenceObj = pickleFixLoad('../TextSegmentation/Pickle_Files/' + fName)
# SeeSentence(sentenceObj)
prediction = algo.predict(sentenceObj, dcsObj)
print(prediction)
if prediction != None:
    print("Accuracy:", Accuracy(prediction, dcsObj))
else:
    print(fName)

['sarva', 'pARqava', 'krI', 'yam', 'ca']
Accuracy: 60.0


In [9]:
c=pickle.load(open('extras/list_of_uniq_cngs.p','rb'))

In [11]:
'62' in c

False

In [25]:
a = np.array([1, 5, 3, 6, 8])
a.argsort()[::-1]

array([4, 3, 1, 2, 0])