In [85]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [152]:
from SktWsegRWR_utf8 import *
from utilities import *
import numpy as np
np.set_printoptions(precision=2, suppress= True)
from sentences import *
from DCS import *
np.set_printoptions(precision=5)

In [137]:
import ProbData
from ProbModels import *

In [5]:
goodDict = pickle.load(open('mergedGood_v2.p', 'rb'))
list(goodDict.keys())[0:10]

['144415.p',
 '172618.p',
 '354565.p',
 '216268.p',
 '389803.p',
 '390332.p',
 '191125.p',
 '401327.p',
 '188914.p',
 '179292.p']

In [147]:
i = 1022
for i in range(200):
    if(goodDict[list(goodDict.keys())[i]] == 'C1020'):
        dcsObj = pickleFixLoad('../Text Segmentation/DCS_pick/' + list(goodDict.keys())[i])
        sentenceObj = pickleFixLoad('../TextSegmentation/corrected_10to20/' + list(goodDict.keys())[i])
#         SeeSentence(sentenceObj)
        (chunkDict, wordList, revMap2Chunk, qu, cngList, verbs) = SentencePreprocess(sentenceObj)
        if(len(wordList) < 7):
            print(list(goodDict.keys())[i], len(wordList))

188914.p 5
416810.p 3
418091.p 4
441958.p 5


In [149]:
f = '441958.p'
dcsObj = pickleFixLoad('../Text Segmentation/DCS_pick/' + f)
sentenceObj = pickleFixLoad('../TextSegmentation/corrected_10to20/' + f)
SeeSentence(sentenceObj)
(chunkDict, wordList, revMap2Chunk, qu, cngList, verbs) = SentencePreprocess(sentenceObj)


kzudrajantavaH    
Analyzing  kzudrajantavaḥ
0 :  kzudra ['kzudra'] [{'compound': ['iic.']}]
9 :  tavas ['tavas'] [{'noun': ['voc. sg. f.']}]
6 :  jantavas ['jantu'] [{'noun': ['nom. pl. m.']}]
6 :  jantavas ['jantu'] [{'noun': ['voc. pl. m.']}]
6 :  jam ['ja'] [{'noun': ['acc. sg. m.', 'acc. sg. n.', 'nom. sg. n.']}]


In [150]:
wordList

['kzudra', 'tavas', 'jantu', 'jantu', 'ja']

In [138]:


pb = ProbModels(fullCo_oc_mat = ProbData.fullCo_oc_mat, unigram_counts = ProbData.unigram_counts,
               cng2cngFullMat = ProbData.cng2cngFullMat, cng2index_dict = ProbData.cng2index_dict,
               w2w_samecng_fullmat=ProbData.w2w_samecng_fullmat, samecng_unigram_counts=ProbData.samecng_unigram_counts)

In [22]:
algo = SktWsegRWR(w2w_modelFunc=pb.get_w2w_mat, t2t_modelFunc=pb.get_cng2cng_mat, )


TypeError: __init__() missing 2 required positional arguments: 'v2t_modelFunc' and 'sameCng_modelFunc'

In [153]:
print(pb.get_w2w_mat(wordList, False))
print()
print(pb.get_w2w_mat(wordList))

[[ 0.       0.       0.33333  0.33333  0.33333]
 [ 0.25     0.       0.25     0.25     0.25   ]
 [ 0.30769  0.       0.       0.       0.69231]
 [ 0.30769  0.       0.       0.       0.69231]
 [ 0.18182  0.       0.40909  0.40909  0.     ]]

[[ 0.       0.00004  0.31792  0.31792  0.36413]
 [ 0.11676  0.       0.16536  0.16536  0.55253]
 [ 0.27325  0.00004  0.       0.02402  0.70268]
 [ 0.27325  0.00004  0.02402  0.       0.70268]
 [ 0.18212  0.00008  0.4089   0.4089   0.     ]]


In [155]:
print(pb.get_w2w_samecng_mat(wordList, False))
print()
print(pb.get_w2w_samecng_mat(wordList))

[[ 0.       0.       0.25     0.25     0.5    ]
 [ 0.       0.       0.       0.       0.     ]
 [ 0.16667  0.       0.       0.       0.83333]
 [ 0.16667  0.       0.       0.       0.83333]
 [ 0.16667  0.       0.41667  0.41667  0.     ]]

[[ 0.       0.00012  0.19006  0.19006  0.61976]
 [ 0.12075  0.       0.1239   0.1239   0.63145]
 [ 0.10353  0.00007  0.       0.01322  0.88319]
 [ 0.10353  0.00007  0.01322  0.       0.88319]
 [ 0.16043  0.00016  0.4197   0.4197   0.     ]]


In [ ]:
v2c_fullMat = pickle.load(open('extras/verbs_vs_cngs_matrix_countonly.p', 'rb'), encoding=u'utf8')
def func(wordList, cngList, verb):
    