In [1]:
import numpy as np

In [39]:
transMat = np.mat([
        [0,0.3,0.7,0,0],
        [0.5,0,0.2,0.3,0],
        [0.2,0.3,0,0.2,0.2],
        [0,0.5,0.1,0,0.4],
        [0,0,0.7,0.3,0]
    ])
print(transMat)
nodes = [0,1,3,4]

[[ 0.   0.3  0.7  0.   0. ]
 [ 0.5  0.   0.2  0.3  0. ]
 [ 0.2  0.3  0.   0.2  0.2]
 [ 0.   0.5  0.1  0.   0.4]
 [ 0.   0.   0.7  0.3  0. ]]


In [52]:
def Floyd_Warshall(nodes, transMat):
    D = np.copy(1/(transMat + 0.00001))
#     D[D > 0] = 1
#     D[D == 0] = np.Inf
    for i in nodes:
        D[i, i] = 0
    print(D)
    for k in nodes:
        D_new = np.zeros(D.shape)
        for i in nodes:
            for j in nodes:
                D_new[i, j] = np.min([D[i,j], D[i, k] + D[k, j]])
        D = D_new

    return(D)

In [53]:
sp = Floyd_Warshall(nodes, transMat)
print(sp)
np.max(sp)
# np.max(shortPath)

[[  0.00000000e+00   3.33322223e+00   1.42855102e+00   1.00000000e+05
    1.00000000e+05]
 [  1.99996000e+00   0.00000000e+00   4.99975001e+00   3.33322223e+00
    1.00000000e+05]
 [  4.99975001e+00   3.33322223e+00   1.00000000e+05   4.99975001e+00
    4.99975001e+00]
 [  1.00000000e+05   1.99996000e+00   9.99900010e+00   0.00000000e+00
    2.49993750e+00]
 [  1.00000000e+05   1.00000000e+05   1.42855102e+00   3.33322223e+00
    0.00000000e+00]]
[[ 0.          3.33322223  0.          6.66644445  9.16638195]
 [ 1.99996     0.          0.          3.33322223  5.83315973]
 [ 0.          0.          0.          0.          0.        ]
 [ 3.99992     1.99996     0.          0.          2.4999375 ]
 [ 7.33314223  5.33318223  0.          3.33322223  0.        ]]


9.1663819534140654

In [60]:
print(transMat)
t = transMat[[1,2,3], :]
print(t[:, [0, 1, 2]])

[[ 0.   0.3  0.7  0.   0. ]
 [ 0.5  0.   0.2  0.3  0. ]
 [ 0.2  0.3  0.   0.2  0.2]
 [ 0.   0.5  0.1  0.   0.4]
 [ 0.   0.   0.7  0.3  0. ]]
[[ 0.5  0.   0.2]
 [ 0.2  0.3  0. ]
 [ 0.   0.5  0.1]]
