In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# from AlgoTestFactory import *

# altf1 = AlgoTestFactory([0, 10000], 15, savePath="Combined_4_test2", storeAccuracies=True)

# altf1.run()

In [3]:
from SktWsegRWR_utf8 import *
import pickle
import ProbData
from ProbModels import *
import multiprocessing
import math
import json
import pprint
import csv
from utilities import *
from IPython.display import display
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import pandas as pd

Dataloader Started[Prob]...
Dataloader Finished[Prob]...


In [15]:
pb = ProbModels(fullCo_oc_mat = ProbData.fullCo_oc_mat, unigram_counts = ProbData.unigram_counts,
               cng2cngFullMat = ProbData.cng2cngFullMat, cng2index_dict = ProbData.cng2index_dict,
               w2w_samecng_fullmat=ProbData.w2w_samecng_fullmat, samecng_unigram_counts=ProbData.samecng_unigram_counts,
               v2c_fullMat = ProbData.v2c_fullMat)

goodFileDict = pickle.load(open('mergedGood_v5.p', 'rb'))
algo = SktWsegRWR(
            w2w_modelFunc = pb.get_w2w_mat, 
            t2t_modelFunc = pb.get_cng2cng_mat,
            v2c_modelFunc = pb.get_v2c_ranking,
            sameCng_modelFunc = pb.get_w2w_samecng_mat,
            partition=[0.25, 0.25, 0.25, 0.1]
        )

In [5]:
# df_pf1 = pd.read_csv('extras/pvbnhi@pf.csv', header=None, names=['file', 'miss', 'miss2'])
# df_pf2 = pd.read_csv('extras/pvbnhi@skt.csv', header=None, names=['file', 'miss', 'miss2'])
# df_pf3 = pd.read_csv('extras/pvbnhi@upd.csv', header=None, names=['file', 'miss', 'miss2'])

# df_pf1['miss'] = df_pf1[df_pf1['miss'] != 'Incomplete chunk']['miss'].astype(int)
# df_pf1 = df_pf1[df_pf1['miss'] == 0]
# df_pf1['folder'] = '../TextSegmentation/Pickle_Files/'

# df_pf2['miss'] = df_pf2[df_pf2['miss'] != 'Incomplete chunk']['miss'].astype(int)
# df_pf2 = df_pf2[df_pf2['miss'] == 0]
# df_pf2['folder'] = '../TextSegmentation/corrected_10to20/'

# df_pf3['miss'] = df_pf3[df_pf3['miss'] != 'Incomplete chunk']['miss'].astype(int)
# df_pf3 = df_pf3[df_pf3['miss'] == 0]
# df_pf3['folder'] = '../TextSegmentation/Updated Pickles/'

# frames = [df_pf1, df_pf2, df_pf3]
# df_pf = pd.concat(frames)
# %reset_selective df_pf1
# %reset_selective df_pf2
# %reset_selective df_pf3
# goodFileDict = {}
# for index, row in df_pf.iterrows():
#     goodFileDict['%d.p' % row['file']] = '%s%d.p' % (row['folder'], row['file'])
len(goodFileDict)

49441

49441

In [14]:
fs = ['31031.p']
np.set_printoptions(precision=4)
# for f in list(goodFileDict.keys())[1:20]:
# for f in list(goodFileDict.keys())[1:100]:
for f in fs:
#     print('=='*20)
    sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
    if(sentenceObj != None):
        result = algo.predict(sentenceObj, dcsObj, verbose = False, eta=0.05)
        if(result != None):
            solution = [rom_slp(c) for arr in dcsObj.lemmas for c in arr]
            ac = Accuracy(result, dcsObj)
            print(f, "\t", ac)

0 1 2
[-0.3659 -1.8959 -2.8059  0.1176]
13
0 1 3
[-0.3659 -1.9459 -2.9559  0.1176]
17
0 5 3
[-0.3659 -2.1959 -3.1059  0.1176]
25
0 5 4
[-0.3659 -2.4459 -3.3059  0.1176]
26
1 1 1
[-0.4159 -2.4959 -3.3559  0.1176]
21
31031.p 	 66.66666666666667


In [29]:
f = '30240.p'
# print(goodFileDict[f])
s, d = loadSentence(f, '../TextSegmentation/Updated Pickles/30240.p')
SeeSentence(s)
SeeDCS(d)

SKT ANALYZE
---------------
na hi kAlopapannena dAnaviGnaH  kfto'rTinA   
Analyzing  na
0 :  na ['na'] [{'indeclinable': ['part.']}]
Analyzing  hi
0 :  hi ['h_1'] [{'indeclinable': ['part.']}]
0 :  hi ['hi'] []
Analyzing  kAlopapannena
0 :  kAla ['kāla_1', 'kāla_2'] [{'compound': ['iic.']}, {'compound': ['iic.']}]
0 :  kA ['km'] [{'noun': ['nom. sg. f.']}]
0 :  kAla ['kāla'] []
1 :  ala ['ala'] [{'compound': ['iic.']}]
1 :  Ala ['āla'] [{'compound': ['iic.']}]
1 :  a ['a'] [{'compound': ['iic.']}]
1 :  upapad ['upapad'] []
2 :  lopa ['lopa'] [{'compound': ['iic.']}]
3 :  upapannena ['panna', 'pad_1'] [{'noun': ['i. sg. n.', 'i. sg. m.']}, {'verb': ['pp.']}]
3 :  upapanna ['panna', 'pad_1'] [{'compound': ['iic.']}, {'verb': ['pp.']}]
3 :  upapanne ['panna', 'pad_1'] [{'noun': ['acc. du. f.', 'nom. du. f.', 'acc. du. n.', 'nom. du. n.', 'loc. sg. n.', 'loc. sg. m.']}, {'verb': ['pp.']}]
3 :  upapannA ['panna', 'pad_1'] [{'noun': ['nom. sg. f.']}, {'verb': ['pp.']}]
6 :  pannena ['panna',

In [48]:
fs = [ '38838.p']
def debugSentences(fs):
    np.set_printoptions(precision=4)
    # for f in list(goodFileDict.keys())[1:20]:
    # for f in list(goodFileDict.keys())[1:100]:
    for f in fs:
    #     print('=='*20)
        sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
        SeeSentence(sentenceObj)
        if(sentenceObj != None):
            result, detail = algo.predict(sentenceObj, dcsObj, verbose = True)
            if(result != None):
                solution = [rom_slp(c) for arr in dcsObj.lemmas for c in arr]
                ac = Accuracy(result, dcsObj)
                print(f, "\t", ac)
#                 display(detail['sentence'])
#                 display(detail['DCSLemmas'])
                solution = [rom_slp(c) for arr in dcsObj.lemmas for c in arr]
                solution_no_pvb = [removePrefix(l) for l in solution]
                print('='*40)
                print(dcsObj.lemmas)
                print(solution_no_pvb)
                display(result)
#                 print(detail['nodeList'])
                print('Initial Query:', detail['initialQuery'])
                for step in range(detail['steps']):
                    print('-'*30)
                    print('Step:', step)
                    print('-'*30)
                    print('Winner:', detail[str(step)]['winner'])
                    print('Removed:', detail[str(step)]['removed'])
                    print('Query:', detail[str(step)]['updated_query'])
        print('='*30)

debugSentences(fs)

SKT ANALYZE
---------------
nAmaBistu samAKyAtA nAradena mahAtmanA   
Analyzing  nAmaBistu
0 :  nAmaBiḥ ['nAman'] [{'noun': ['i. pl. n.']}]
7 :  tu ['tu'] [{'indeclinable': ['conj.']}]
Analyzing  samAKyAtA
0 :  sama ['sama'] [{'compound': ['iic.']}]
0 :  samA ['samA'] [{'compound': ['iic.']}]
0 :  samA ['samA', 'sama'] [{'noun': ['nom. sg. f.']}, {'noun': ['nom. sg. f.']}]
0 :  sa ['tad'] [{'noun': ['nom. sg. m.']}]
0 :  samAKyA ['samAKyA'] [-190]
2 :  mA ['mA'] [{'indeclinable': ['part.']}]
2 :  mA ['mad'] [{'noun': ['acc. sg. *']}]
3 :  AKyAtAḥ ['KyAta', 'KyA'] [{'noun': ['acc. pl. f.', 'nom. pl. f.', 'nom. pl. m.']}, {'verb': ['pp.']}]
3 :  AKyAtA ['KyA', 'KyAta', 'KyA'] [{'verb': [['pp.']], 'noun': ['i. sg. n.', 'i. sg. m.'], 'verbform': ['"http:sanskrit.inria.frMW75.html#H_khyaa"']}, {'verb': ['ppr. [2] ac.', ['pp.']], 'verbform': ['"http:sanskrit.inria.frMW75.html#H_khyaata"']}, {'verb': [['pp.']], 'noun': ['nom. sg. f.'], 'verbform': ['"http:sanskrit.inria.frMW75.html#H_khyaa"']

['nAman',
 'tu',
 'tad',
 'tad',
 'na',
 'na',
 'mad',
 'mahant',
 'Atman',
 'da',
 'a',
 'a']

Initial Query: [0, 1]
------------------------------
Step: 0
------------------------------
Winner: (6, 'sa', 'tad', 29)
Removed: [(2, 'sama', 'sama', 3), (3, 'samA', 'samA', 3), (4, 'samA', 'samA', 30), (5, 'samA', 'sama', 30), (7, 'samAKyA', 'samAKyA', -190)]
Query: [0, 1, 6]
------------------------------
Step: 1
------------------------------
Winner: (33, 'tAḥ', 'tad', 40)
Removed: [(32, 'tAḥ', 'tad', 80), (10, 'AKyAtAḥ', 'KyAta', 80), (11, 'AKyAtAḥ', 'KyAta', 40), (12, 'AKyAtAḥ', 'KyAta', 39), (13, 'AKyAtAḥ', 'KyA', -190), (14, 'AKyAtA', 'KyA', 89), (15, 'AKyAtA', 'KyA', 91), (16, 'AKyAtA', 'KyAta', -190), (17, 'AKyAtA', 'KyAta', -10), (18, 'AKyAtA', 'KyA', 30), (19, 'AKyAtA', 'KyA', -73), (22, 'KyAtAḥ', 'KyAta', 80), (23, 'KyAtAḥ', 'KyAta', 40), (24, 'KyAtAḥ', 'KyAta', 39), (25, 'KyAtAḥ', 'KyA', -190), (26, 'KyAtA', 'KyA', 89), (27, 'KyAtA', 'KyA', 91), (28, 'KyAtA', 'KyAta', -190), (29, 'KyAtA', 'KyAta', -10), (30, 'KyAtA', 'KyA', 30), (31, 'KyAtA', 'KyA', -73)]
Query: [0, 1, 6,

In [18]:
# with open('.temp/sandhi_encounters.csv', 'w') as fh:
#     fcsv = csv.writer(fh)
#     fcsv.writerow(['left', 'right', 'derivations', 'word_left', 'word_right', 'pos_left', 'pos_right'])
# np.set_printoptions(precision=6)
# for f in list(goodFileDict.keys())[90:91]:
for f in list(goodFileDict.keys())[0:100]:
# for f in fullfs:
    sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
    if(sentenceObj != None):
        result = algo.predict(sentenceObj, dcsObj, eta = 0.05)
        if(result != None):
            ac = Accuracy(result, dcsObj)
            solution = [rom_slp(c) for arr in dcsObj.lemmas for c in arr]
#             print(result)
#             print('vs')
#             print(solution)

            print(f, "\t", ac)

40559.p 	 85.71428571428571
9882.p 	 57.142857142857146
9322.p 	 70.0
46252.p 	 42.857142857142854
5914.p 	 28.571428571428573
8100.p 	 84.61538461538461
20991.p 	 75.0
9956.p 	 87.5
30191.p 	 42.857142857142854
1965.p 	 50.0
33847.p 	 57.142857142857146
36166.p 	 66.66666666666667
434717.p 	 80.0
121160.p 	 77.77777777777777
416689.p 	 50.0
155344.p 	 83.33333333333333
25556.p 	 87.5
12103.p 	 57.142857142857146
18601.p 	 85.71428571428571
148399.p 	 62.5
44388.p 	 50.0
40786.p 	 70.0
37439.p 	 71.42857142857143
258081.p 	 85.71428571428571
5115.p 	 80.0
10770.p 	 66.66666666666667
34794.p 	 75.0
38614.p 	 42.857142857142854
1580.p 	 100.0
187398.p 	 66.66666666666667
17538.p 	 83.33333333333333
27724.p 	 77.77777777777777
163.p 	 33.333333333333336
22987.p 	 85.71428571428571
45085.p 	 87.5
16923.p 	 100.0
50833.p 	 87.5
4509.p 	 60.0
337386.p 	 100.0
222364.p 	 71.42857142857143
139573.p 	 100.0
9889.p 	 50.0
36265.p 	 57.142857142857146
228536.p 	 42.857142857142854
34139.p 	 85.71

In [31]:
# fullfs = ['105587.p','293473.p','379245.p']
fullfs = ['302864.p', '292204.p', '161425.p', '128533.p', '265112.p', '16349.p', '320178.p', '334655.p', '331468.p', '365975.p', '434538.p', '148267.p', '340997.p', '204751.p', '289589.p', '423330.p', '276728.p', '105056.p', '325962.p', '383515.p', '60055.p', '228316.p', '192549.p', '169215.p', '393452.p', '433996.p', '440103.p', '68686.p', '157189.p', '440567.p']

In [200]:
fullfs = ['302864.p', '292204.p', '161425.p', '128533.p', '265112.p', '16349.p', '320178.p', '334655.p', '331468.p', '365975.p', '434538.p', '148267.p', '340997.p', '204751.p', '289589.p', '423330.p', '276728.p', '105056.p', '325962.p', '383515.p', '60055.p', '228316.p', '192549.p', '169215.p', '393452.p', '433996.p', '440103.p', '68686.p', '157189.p', '440567.p']
def GetSomeJSON():
    lowScore = []
    midScore = []
    highScore = []
    np.set_printoptions(precision=4)
#     for i in range(1, 400):
#         f = list(goodFileDict.keys())[i]
#     print(len(fullfs))
    for f in fullfs:
        sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
        if(sentenceObj != None):
            result, runDetails = algo.predict(sentenceObj, dcsObj, verbose = True)

            if(result != None):
                runDetails['file'] = f
                ac = runDetails['accuracy']
#                 print(f, ac)

                # CODE FOR SELECTING FILES 
#                 if(i%100 == 0):
#                     print('Chekpoint:', i)
                if(ac <= 40):
                    lowScore.append(runDetails)
                elif (ac <= 60):
                    if(ac >= 45):
                        midScore.append(runDetails)
                elif (ac <= 100):
                    if(ac >= 80):
                        highScore.append(runDetails)

    print('Lowscore files found:', len(lowScore))
    print('Midscore files found:', len(midScore))
    print('Highscore files found:', len(highScore))

    lowScore = lowScore[0:10]
    midScore = midScore[0:10]
    highScore = highScore[0:10]
    pickle.dump(lowScore, open('lowScore.p', 'wb'))
    pickle.dump(midScore, open('midScore.p', 'wb'))
    pickle.dump(highScore, open('highScore.p', 'wb'))

#=================================================================
GetSomeJSON()

Lowscore files found: 4
Midscore files found: 7
Highscore files found: 9


In [38]:
def MacroAccuracy():
    allAcs = []
    np.set_printoptions(precision=4)
    gfs = list(goodFileDict.keys())
    for i in range(400):
#     for i in range(10):
        f = gfs[i]
        sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
        if(sentenceObj != None):
            result = algo.predict(sentenceObj, dcsObj, verbose = False)
            
            if(result != None):
#                 print(result)
#                 print(dcsObj.lemmas)
                ac = Accuracy(result, dcsObj)
                allAcs.append(ac)
#                 print(f, ac)

                # CODE FOR SELECTING FILES 
                if(i%100 == 0):
                    print('Chekpoint:', i)
    allAcs = np.array(allAcs)
    return allAcs


#=================================================================
allAcs = MacroAccuracy()

Chekpoint: 0
Chekpoint: 100
Chekpoint: 300


In [44]:
print(len(allAcs))
print(np.mean(allAcs))
# the histogram of the data
n, bins, patches = plt.hist(allAcs, 40, normed=False)

plt.xlabel('MicroAccuracy')
plt.ylabel('Count')
plt.title('Histogram of MicroAccuracy')
plt.grid(True)
plt.show()

print('Macro Accuracy %:', 100*np.sum(n[(bins[::] > 95)[:-1:]])/np.sum(n))

348
76.8498538275
Macro Accuracy %: 20.6896551724


In [ ]:
def SeeSomeJSON(region = 'mid', files = ['lowScore.p', 'midScore.p', 'highScore.p']):
    np.set_printoptions(precision=3)
    if region == 'low':
        p = pickleFixLoad(files[0])
    elif region == 'mid':
        p = pickleFixLoad(files[1])
    else:
        p = pickleFixLoad(files[2])
#     for pf in p:
#         print(pf['file'])
    n_steps = p[0]['steps']
    for s in range(n_steps):
        
        print('Step:', s)
        print('='*20)
        
        for key, val in p[0][str(s)].items():
            print(key, ":")
            print(val)
            print('-'*20)
        
SeeSomeJSON('low')
print('='*20)
SeeSomeJSON('mid')
print('='*20)
SeeSomeJSON('high')

In [68]:
def ArePredictionsOK():
    with open('.temp/weird.csv', 'w') as fh:
        wcsv = csv.writer(fh)
        wcsv.writerow(['filename', 'sentence', 'solution', 'prediction'])
        np.set_printoptions(precision=4)
        badCount = 0
        for i in range(1, 600):
            f = list(goodFileDict.keys())[i]

            sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
            if(sentenceObj != None):
                result = algo.predict(sentenceObj, dcsObj, verbose = False)
                if(result != None):            
                    solution = [rom_slp(c) for arr in dcsObj.lemmas for c in arr]
                    ac = Accuracy(result, dcsObj)
                    if ac >= 100 and len(result) != len(solution):
                        badCount += 1
                        if(badCount%10 == 0):
                            print("="*40)
                        sline = [f, sentenceObj.sentence, solution, result]
                        wcsv.writerow(sline)
        print(badCount, 'weird predictions encountered.')
        
ArePredictionsOK()

35 weird predictions encountered.


In [9]:
sentenceObj, dcsObj = loadSentence('1.p', '../TextSegmentation/corrected_10to20/1.p')
SeeSentence(sentenceObj)

SKT ANALYZE
---------------
paYca ratnAni muKyAni coparatnacatuzwayam   
Analyzing: paYca
-------------------------
Analyzing: ratnAni
0 : ratnAni [0, 'ratna', 81] [1, 'ratna', 41] 
0 : ratnAni [2, 'ratna', 61] 
-------------------------
Analyzing: muKyAni
0 : muKyAni [3, 'muKya', 81] [4, 'muKya', 41] 
0 : muKyAni [5, 'muKya', 61] 
-------------------------
Analyzing: coparatnacatuzwayam
0 : ca [6, 'ca', 2] 
9 : catuzwayam [7, 'catuzwaya', 31] [8, 'catuzwaya', 69] [9, 'catuzwaya', 71] 
4 : ratna [10, 'ratna', 3] 
1 : uparatna [11, 'uparatna', 3] 
1 : Upa [12, 'vap', -158] 
-------------------------
Analyzing  paYca
0 :  paYca [] []
Analyzing  ratnAni
0 :  ratnAni ['ratna'] [{'noun': ['acc. pl. n.', 'nom. pl. n.']}]
0 :  ratnAni ['ratna'] [{'noun': ['voc. pl. n.']}]
Analyzing  muKyAni
0 :  muKyAni ['muKya'] [{'noun': ['acc. pl. n.', 'nom. pl. n.']}]
0 :  muKyAni ['muKya'] [{'noun': ['voc. pl. n.']}]
Analyzing  coparatnacatuzwayam
0 :  ca ['ca'] [{'indeclinable': ['conj.']}]
9 :  catuzwa

In [8]:
SeeDCS(dcsObj)

DCS ANALYZE
---------------
upacAreRa SIlena rUpayOvanasaMpadA   
[['upacāra'], ['śīla'], ['rūpa', 'yauvana', 'sampad']]
Lemmas: ['upacAra', 'SIla', 'rUpa', 'yOvana', 'sampad']
[['89'], ['91'], ['3', '3', '90']]



In [7]:
def CSVforSupervised():
    np.set_printoptions(precision=4)
    # Clean the csv files
    metPerfFH = open('.temp/metPerfFH.csv', 'w')
    metPerfFH_bin = open('.temp/metPerfFH_bin.csv', 'w')

    metPerfFH.write('w2w,t2t,w2w_samecng,InDCS\n')
    metPerfFH_bin.write('w2w,t2t,w2w_samecng,InDCS\n')

    metPerfFH.close()
    metPerfFH_bin.close()
    ######################
    gfl = list(goodFileDict.keys())
    for i in range(0, 11000):
        f = gfl[i]
        if(i%250 == 0):
            print('Checkpoint:', i)
        sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
        
        if(sentenceObj != None):
            result, runDetails = algo.predict(sentenceObj, dcsObj, verbose = True)




In [ ]:
np.set_printoptions(precision=6)
jsonBatch = []
for f_ in lowScore[0:10]:
    f = f_[0]
    sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
    if(sentenceObj != None):
        result, runDetails = algo.predict(sentenceObj, dcsObj, verbose = True)
        runDetails['file'] = f
        jsonBatch.append(runDetails)
pickle.dump(jsonBatch, open('.temp/lowScore.p','wb'))
print('33 % Complete')
#################################################################
jsonBatch = []
for f_ in midScore[0:10]:
    f = f_[0]
    sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
    if(sentenceObj != None):
        result, runDetails = algo.predict(sentenceObj, dcsObj, verbose = True)
        runDetails['file'] = f
        jsonBatch.append(runDetails)
pickle.dump(jsonBatch, open('.temp/midScore.p','wb'))
print('67 % Complete')
#################################################################
jsonBatch = []
for f_ in highScore[0:10]:
    f = f_[0]
    sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
    if(sentenceObj != None):
        result, runDetails = algo.predict(sentenceObj, dcsObj, verbose = True)
        runDetails['file'] = f
        jsonBatch.append(runDetails)
print(pprint.pprint(jsonBatch))
pickle.dump(jsonBatch, open('.temp/highScore.p','wb'))
print('100 % Complete')

In [195]:
a = np.array([1,2,3,4,5])
a[:-1:]

array([1, 2, 3, 4])