In [6]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
# from AlgoTestFactory import *

# altf1 = AlgoTestFactory([0, 10000], 15, savePath="Combined_4_test2", storeAccuracies=True)

# altf1.run()

In [8]:
from SktWsegRWR_utf8 import *
import pickle
import ProbData
from ProbModels import *
import multiprocessing
import math
import json
import pprint
import csv
from utilities import *
from IPython.display import display
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import pandas as pd

In [9]:
pb = ProbModels(fullCo_oc_mat = ProbData.fullCo_oc_mat, unigram_counts = ProbData.unigram_counts,
               cng2cngFullMat = ProbData.cng2cngFullMat, cng2index_dict = ProbData.cng2index_dict,
               w2w_samecng_fullmat=ProbData.w2w_samecng_fullmat, samecng_unigram_counts=ProbData.samecng_unigram_counts,
               v2c_fullMat = ProbData.v2c_fullMat)

goodFileDict = pickle.load(open('mergedGood_CompatSKT.p', 'rb'))

algo = SktWsegRWR(
            w2w_modelFunc = pb.get_w2w_mat, 
            t2t_modelFunc = pb.get_cng2cng_mat,
            v2c_modelFunc = pb.get_v2c_ranking,
            sameCng_modelFunc = pb.get_w2w_samecng_mat,
            partition=[0.25, 0.25, 0.25, 0.1]
        )

In [8]:
# goodFileDict = {}
# new_flist = os.listdir('../TextSegmentation/CompatSKT/')
# for f in new_flist:
#     goodFileDict[f] = '../TextSegmentation/CompatSKT/' + f
# pickle.dump(goodFileDict, open('mergedGood_CompatSKT.p', 'wb'))

In [10]:
# df_pf1 = pd.read_csv('extras/pvbnhi@pf.csv', header=None, names=['file', 'miss', 'miss2'])
# df_pf2 = pd.read_csv('extras/pvbnhi@skt.csv', header=None, names=['file', 'miss', 'miss2'])
# df_pf3 = pd.read_csv('extras/pvbnhi@upd.csv', header=None, names=['file', 'miss', 'miss2'])

# df_pf1['miss'] = df_pf1[df_pf1['miss'] != 'Incomplete chunk']['miss'].astype(int)
# df_pf1 = df_pf1[df_pf1['miss'] == 0]
# df_pf1['folder'] = '../TextSegmentation/Pickle_Files/'

# df_pf2['miss'] = df_pf2[df_pf2['miss'] != 'Incomplete chunk']['miss'].astype(int)
# df_pf2 = df_pf2[df_pf2['miss'] == 0]
# df_pf2['folder'] = '../TextSegmentation/corrected_10to20/'

# df_pf3['miss'] = df_pf3[df_pf3['miss'] != 'Incomplete chunk']['miss'].astype(int)
# df_pf3 = df_pf3[df_pf3['miss'] == 0]
# df_pf3['folder'] = '../TextSegmentation/Updated Pickles/'

# frames = [df_pf1, df_pf2, df_pf3]
# df_pf = pd.concat(frames)
# %reset_selective df_pf1
# %reset_selective df_pf2
# %reset_selective df_pf3
# goodFileDict = {}
# for index, row in df_pf.iterrows():
#     goodFileDict['%d.p' % row['file']] = '%s%d.p' % (row['folder'], row['file'])
len(goodFileDict)

100078

49441

In [66]:
algo.partition = np.array([0.33,0.33,0.33,0.01])

In [67]:
fs = ['31031.p2']
np.set_printoptions(precision=4)
# for f in list(goodFileDict.keys())[1:20]:
# for f in list(goodFileDict.keys())[1:100]:
for f in fs:
#     print('=='*20)
    sentenceObj, dcsObj = loadSentence_nopre(f, goodFileDict[f])
    if(sentenceObj != None):
        result = algo.predict(sentenceObj, dcsObj, verbose = False, supervised=True, eta=0.1)
        if(result != None):
            solution = [rom_slp(c) for arr in dcsObj.lemmas for c in arr]
            ac = Accuracy(result, dcsObj)
            print(f, "\t", ac)

31031.p2 	 66.66666666666667


In [29]:
f = '30240.p'
# print(goodFileDict[f])
s, d = loadSentence(f, '../TextSegmentation/Updated Pickles/30240.p')
SeeSentence(s)
SeeDCS(d)

SKT ANALYZE
---------------
na hi kAlopapannena dAnaviGnaH  kfto'rTinA   
Analyzing  na
0 :  na ['na'] [{'indeclinable': ['part.']}]
Analyzing  hi
0 :  hi ['h_1'] [{'indeclinable': ['part.']}]
0 :  hi ['hi'] []
Analyzing  kAlopapannena
0 :  kAla ['kāla_1', 'kāla_2'] [{'compound': ['iic.']}, {'compound': ['iic.']}]
0 :  kA ['km'] [{'noun': ['nom. sg. f.']}]
0 :  kAla ['kāla'] []
1 :  ala ['ala'] [{'compound': ['iic.']}]
1 :  Ala ['āla'] [{'compound': ['iic.']}]
1 :  a ['a'] [{'compound': ['iic.']}]
1 :  upapad ['upapad'] []
2 :  lopa ['lopa'] [{'compound': ['iic.']}]
3 :  upapannena ['panna', 'pad_1'] [{'noun': ['i. sg. n.', 'i. sg. m.']}, {'verb': ['pp.']}]
3 :  upapanna ['panna', 'pad_1'] [{'compound': ['iic.']}, {'verb': ['pp.']}]
3 :  upapanne ['panna', 'pad_1'] [{'noun': ['acc. du. f.', 'nom. du. f.', 'acc. du. n.', 'nom. du. n.', 'loc. sg. n.', 'loc. sg. m.']}, {'verb': ['pp.']}]
3 :  upapannA ['panna', 'pad_1'] [{'noun': ['nom. sg. f.']}, {'verb': ['pp.']}]
6 :  pannena ['panna',

In [96]:
algo.partition = np.array([0.33,0.33,0.33,0.01])
fs = ['82508.p2']
def debugSentences(fs):
    np.set_printoptions(precision=4)
    # for f in list(goodFileDict.keys())[1:20]:
    # for f in list(goodFileDict.keys())[1:100]:
    for f in fs:
    #     print('=='*20)
        sentenceObj, dcsObj = loadSentence_nopre(f, goodFileDict[f])
        solution = [rom_slp(c) for arr in dcsObj.lemmas for c in arr]
        solution_no_pvb = [removePrefix(l) for l in solution]
#         print('='*40)
#         print(dcsObj.lemmas)
#         print(solution)

#         SeeSentence(sentenceObj)
        if(sentenceObj != None):
            result, detail = algo.predict(sentenceObj, dcsObj, verbose = True)
            if(result != None):
                solution = [rom_slp(c) for arr in dcsObj.lemmas for c in arr]
                ac = Accuracy(result, dcsObj)
                print(f, "\t", ac)
#                 display(detail['sentence'])
                display(detail['DCSLemmas'])
                
                display(result)
# #                 print(detail['nodeList'])
#                 print('Initial Query:', detail['initialQuery'])
#                 for step in range(detail['steps']):
#                     print('-'*30)
#                     print('Step:', step)
#                     print('-'*30)
#                     print('Winner:', detail[str(step)]['winner'])
#                     print('Removed:', detail[str(step)]['removed'])
#                     print('Query:', detail[str(step)]['updated_query'])
#                     print(detail[str(step)]['w2w_samecng_score'])
#         print('='*30)

debugSentences(fs)

After: W2W
[[ 0.2563  0.2536  0.0354  0.1954  0.1974  0.7734  0.1     0.6095  0.5721
   0.1131  0.1131  0.1123  0.1     0.0021  0.0023  0.0023  0.      0.      0.
   0.1769  0.3077  0.      0.1     0.      0.      0.0004  0.      0.
   0.0072]]
After: T2T
[[  2.9254e+21   2.2660e+21   1.6927e+22   1.3018e+22   2.2946e+21
    5.5750e+22   1.0000e-01   7.2688e+21   6.4922e+21   7.1451e+21
    7.1453e+21   5.0984e+21   1.0000e-01   5.6079e+21   7.2715e+21
    6.1080e+21   1.6446e+22   6.7288e+21   6.3132e+21   4.3810e+18
    1.7991e+22   3.0832e+19   1.0000e-01   7.0924e+19   3.2733e+19
    1.4297e+21   4.9568e+20   9.7122e+17   1.4297e+21]]
After: SAMECNG
[[  1.6903e+87   1.6612e+87   2.5497e+86   1.5655e+85   1.5689e+85
    1.1947e+88   1.0000e-01   1.9101e+87   1.7552e+87   3.0127e+86
    3.0127e+86   3.7971e+86   1.0000e-01   1.0379e+85   1.0621e+85
    1.0621e+85   1.8214e+82   3.6428e+82   3.6428e+82   2.6761e+85
    3.4844e+87   3.6447e+82   1.0000e-01   1.8224e+82   1.8224e+82
   

[['idam'],
 ['vacana', 'krama'],
 ['tad'],
 ['eka'],
 ['api'],
 ['dUzaRa'],
 ['tvad'],
 ['na'],
 ['lakzay']]

['a',
 'krama',
 'api',
 'na',
 'tu',
 'ay',
 'tad',
 'idam',
 'vacana',
 'eka',
 'lakzay',
 'dUzaRa']

In [78]:
algo.partition = np.array([0.33,0.33,0.33,0.01])
for f in list(goodFileDict.keys())[0:100]:
# for f in fullfs:
    sentenceObj, dcsObj = loadSentence_nopre(f, goodFileDict[f])
    if(sentenceObj != None):
        result = algo.predict(sentenceObj, dcsObj, supervised=True, eta = 0.05)
        if(result != None):
            ac = Accuracy(result, dcsObj)
            solution = [rom_slp(c) for arr in dcsObj.lemmas for c in arr]
#             print(result)
#             print('vs')
#             print(solution)

            print(f, "\t", ac)

0.0720515870239 1.03805739308 1.10199235197
[ 0.37  0.31  0.31  0.01]
-0.0829780247489 1.04037325339 1.0251841807
[ 0.41  0.29  0.29  0.01]
-0.096081986552 1.0448442431 1.03867364203
[ 0.46  0.26  0.26  0.01]
-0.00424858932831 1.05712649793 1.03269804593
[ 0.52  0.23  0.23  0.02]
0.0338245094703 1.06289840165 1.03453155586
[ 0.58  0.2   0.2   0.02]
0.00327299460577 1.06906916623 1.00806680512
[ 0.64  0.17  0.17  0.02]
0.00294987254253 1.08229308977 1.0066103262
[ 0.72  0.13  0.13  0.02]
0.00350068267389 1.08646819477 1.00559497982
[ 0.8   0.08  0.09  0.02]
0.0034003994202 1.06427084529 1.00541752497
[ 0.89  0.03  0.05  0.03]
-1.00000466589 0 0
[ 0.9   0.03  0.05  0.03]
80372.p2 	 75.0
0.0748932132936 1.08623362675 1.0803316283
[ 1.01 -0.03 -0.01  0.03]
-0.00965799057896 1.09313561385 1.10050968905
[ 1.13 -0.09 -0.07  0.03]
0.0217947269203 1.10068806287 1.09299023429
[ 1.27 -0.17 -0.14  0.04]
-0.0238100238917 1.10174682891 1.03508686412
[ 1.43 -0.25 -0.22  0.04]
0.0530891341314 1.042729

In [75]:
print(algo.partition)
algo.partition/np.sum(algo.partition)

[ nan  nan  nan  nan]


array([ nan,  nan,  nan,  nan])

In [31]:
# fullfs = ['105587.p','293473.p','379245.p']
fullfs = ['302864.p', '292204.p', '161425.p', '128533.p', '265112.p', '16349.p', '320178.p', '334655.p', '331468.p', '365975.p', '434538.p', '148267.p', '340997.p', '204751.p', '289589.p', '423330.p', '276728.p', '105056.p', '325962.p', '383515.p', '60055.p', '228316.p', '192549.p', '169215.p', '393452.p', '433996.p', '440103.p', '68686.p', '157189.p', '440567.p']

In [200]:
fullfs = ['302864.p', '292204.p', '161425.p', '128533.p', '265112.p', '16349.p', '320178.p', '334655.p', '331468.p', '365975.p', '434538.p', '148267.p', '340997.p', '204751.p', '289589.p', '423330.p', '276728.p', '105056.p', '325962.p', '383515.p', '60055.p', '228316.p', '192549.p', '169215.p', '393452.p', '433996.p', '440103.p', '68686.p', '157189.p', '440567.p']
def GetSomeJSON():
    lowScore = []
    midScore = []
    highScore = []
    np.set_printoptions(precision=4)
#     for i in range(1, 400):
#         f = list(goodFileDict.keys())[i]
#     print(len(fullfs))
    for f in fullfs:
        sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
        if(sentenceObj != None):
            result, runDetails = algo.predict(sentenceObj, dcsObj, verbose = True)

            if(result != None):
                runDetails['file'] = f
                ac = runDetails['accuracy']
#                 print(f, ac)

                # CODE FOR SELECTING FILES 
#                 if(i%100 == 0):
#                     print('Chekpoint:', i)
                if(ac <= 40):
                    lowScore.append(runDetails)
                elif (ac <= 60):
                    if(ac >= 45):
                        midScore.append(runDetails)
                elif (ac <= 100):
                    if(ac >= 80):
                        highScore.append(runDetails)

    print('Lowscore files found:', len(lowScore))
    print('Midscore files found:', len(midScore))
    print('Highscore files found:', len(highScore))

    lowScore = lowScore[0:10]
    midScore = midScore[0:10]
    highScore = highScore[0:10]
    pickle.dump(lowScore, open('lowScore.p', 'wb'))
    pickle.dump(midScore, open('midScore.p', 'wb'))
    pickle.dump(highScore, open('highScore.p', 'wb'))

#=================================================================
GetSomeJSON()

Lowscore files found: 4
Midscore files found: 7
Highscore files found: 9


In [38]:
def MacroAccuracy():
    allAcs = []
    np.set_printoptions(precision=4)
    gfs = list(goodFileDict.keys())
    for i in range(400):
#     for i in range(10):
        f = gfs[i]
        sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
        if(sentenceObj != None):
            result = algo.predict(sentenceObj, dcsObj, verbose = False)
            
            if(result != None):
#                 print(result)
#                 print(dcsObj.lemmas)
                ac = Accuracy(result, dcsObj)
                allAcs.append(ac)
#                 print(f, ac)

                # CODE FOR SELECTING FILES 
                if(i%100 == 0):
                    print('Chekpoint:', i)
    allAcs = np.array(allAcs)
    return allAcs


#=================================================================
allAcs = MacroAccuracy()

Chekpoint: 0
Chekpoint: 100
Chekpoint: 300


In [44]:
print(len(allAcs))
print(np.mean(allAcs))
# the histogram of the data
n, bins, patches = plt.hist(allAcs, 40, normed=False)

plt.xlabel('MicroAccuracy')
plt.ylabel('Count')
plt.title('Histogram of MicroAccuracy')
plt.grid(True)
plt.show()

print('Macro Accuracy %:', 100*np.sum(n[(bins[::] > 95)[:-1:]])/np.sum(n))

348
76.8498538275
Macro Accuracy %: 20.6896551724


In [ ]:
def SeeSomeJSON(region = 'mid', files = ['lowScore.p', 'midScore.p', 'highScore.p']):
    np.set_printoptions(precision=3)
    if region == 'low':
        p = pickleFixLoad(files[0])
    elif region == 'mid':
        p = pickleFixLoad(files[1])
    else:
        p = pickleFixLoad(files[2])
#     for pf in p:
#         print(pf['file'])
    n_steps = p[0]['steps']
    for s in range(n_steps):
        
        print('Step:', s)
        print('='*20)
        
        for key, val in p[0][str(s)].items():
            print(key, ":")
            print(val)
            print('-'*20)
        
SeeSomeJSON('low')
print('='*20)
SeeSomeJSON('mid')
print('='*20)
SeeSomeJSON('high')

In [68]:
def ArePredictionsOK():
    with open('.temp/weird.csv', 'w') as fh:
        wcsv = csv.writer(fh)
        wcsv.writerow(['filename', 'sentence', 'solution', 'prediction'])
        np.set_printoptions(precision=4)
        badCount = 0
        for i in range(1, 600):
            f = list(goodFileDict.keys())[i]

            sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
            if(sentenceObj != None):
                result = algo.predict(sentenceObj, dcsObj, verbose = False)
                if(result != None):            
                    solution = [rom_slp(c) for arr in dcsObj.lemmas for c in arr]
                    ac = Accuracy(result, dcsObj)
                    if ac >= 100 and len(result) != len(solution):
                        badCount += 1
                        if(badCount%10 == 0):
                            print("="*40)
                        sline = [f, sentenceObj.sentence, solution, result]
                        wcsv.writerow(sline)
        print(badCount, 'weird predictions encountered.')
        
ArePredictionsOK()

35 weird predictions encountered.


In [9]:
sentenceObj, dcsObj = loadSentence('1.p', '../TextSegmentation/corrected_10to20/1.p')
SeeSentence(sentenceObj)

SKT ANALYZE
---------------
paYca ratnAni muKyAni coparatnacatuzwayam   
Analyzing: paYca
-------------------------
Analyzing: ratnAni
0 : ratnAni [0, 'ratna', 81] [1, 'ratna', 41] 
0 : ratnAni [2, 'ratna', 61] 
-------------------------
Analyzing: muKyAni
0 : muKyAni [3, 'muKya', 81] [4, 'muKya', 41] 
0 : muKyAni [5, 'muKya', 61] 
-------------------------
Analyzing: coparatnacatuzwayam
0 : ca [6, 'ca', 2] 
9 : catuzwayam [7, 'catuzwaya', 31] [8, 'catuzwaya', 69] [9, 'catuzwaya', 71] 
4 : ratna [10, 'ratna', 3] 
1 : uparatna [11, 'uparatna', 3] 
1 : Upa [12, 'vap', -158] 
-------------------------
Analyzing  paYca
0 :  paYca [] []
Analyzing  ratnAni
0 :  ratnAni ['ratna'] [{'noun': ['acc. pl. n.', 'nom. pl. n.']}]
0 :  ratnAni ['ratna'] [{'noun': ['voc. pl. n.']}]
Analyzing  muKyAni
0 :  muKyAni ['muKya'] [{'noun': ['acc. pl. n.', 'nom. pl. n.']}]
0 :  muKyAni ['muKya'] [{'noun': ['voc. pl. n.']}]
Analyzing  coparatnacatuzwayam
0 :  ca ['ca'] [{'indeclinable': ['conj.']}]
9 :  catuzwa

In [8]:
SeeDCS(dcsObj)

DCS ANALYZE
---------------
upacAreRa SIlena rUpayOvanasaMpadA   
[['upacāra'], ['śīla'], ['rūpa', 'yauvana', 'sampad']]
Lemmas: ['upacAra', 'SIla', 'rUpa', 'yOvana', 'sampad']
[['89'], ['91'], ['3', '3', '90']]



In [7]:
def CSVforSupervised():
    np.set_printoptions(precision=4)
    # Clean the csv files
    metPerfFH = open('.temp/metPerfFH.csv', 'w')
    metPerfFH_bin = open('.temp/metPerfFH_bin.csv', 'w')

    metPerfFH.write('w2w,t2t,w2w_samecng,InDCS\n')
    metPerfFH_bin.write('w2w,t2t,w2w_samecng,InDCS\n')

    metPerfFH.close()
    metPerfFH_bin.close()
    ######################
    gfl = list(goodFileDict.keys())
    for i in range(0, 11000):
        f = gfl[i]
        if(i%250 == 0):
            print('Checkpoint:', i)
        sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
        
        if(sentenceObj != None):
            result, runDetails = algo.predict(sentenceObj, dcsObj, verbose = True)




In [ ]:
np.set_printoptions(precision=6)
jsonBatch = []
for f_ in lowScore[0:10]:
    f = f_[0]
    sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
    if(sentenceObj != None):
        result, runDetails = algo.predict(sentenceObj, dcsObj, verbose = True)
        runDetails['file'] = f
        jsonBatch.append(runDetails)
pickle.dump(jsonBatch, open('.temp/lowScore.p','wb'))
print('33 % Complete')
#################################################################
jsonBatch = []
for f_ in midScore[0:10]:
    f = f_[0]
    sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
    if(sentenceObj != None):
        result, runDetails = algo.predict(sentenceObj, dcsObj, verbose = True)
        runDetails['file'] = f
        jsonBatch.append(runDetails)
pickle.dump(jsonBatch, open('.temp/midScore.p','wb'))
print('67 % Complete')
#################################################################
jsonBatch = []
for f_ in highScore[0:10]:
    f = f_[0]
    sentenceObj, dcsObj = loadSentence(f, goodFileDict[f])
    if(sentenceObj != None):
        result, runDetails = algo.predict(sentenceObj, dcsObj, verbose = True)
        runDetails['file'] = f
        jsonBatch.append(runDetails)
print(pprint.pprint(jsonBatch))
pickle.dump(jsonBatch, open('.temp/highScore.p','wb'))
print('100 % Complete')

In [195]:
a = np.array([1,2,3,4,5])
a[:-1:]

array([1, 2, 3, 4])

In [24]:
rom_slp('anuṣṭhāna')

'anuzWAna'