In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import KFold
from IPython.display import display

In [2]:
df_bin = pd.read_csv('extras/metPerfFH_bin.csv')
df_rank = pd.read_csv('extras/metPerfFH.csv')
df_bin = df_bin[df_bin['w2w'] + df_bin['t2t'] + df_bin['w2w_samecng'] > 0]
df_rank['w2w'] = 1/(1 + df_rank['w2w'])
df_rank['t2t'] = 1/(1 + df_rank['t2t'])
df_rank['w2w_samecng'] = 1/(1 + df_rank['w2w_samecng'])

In [3]:
df_bin

w2w  t2t  w2w_samecng  InDCS
0        0    0            1      1
2        1    1            0      1
3        0    0            1      1
4        1    1            1      1
5        0    1            1      1
6        0    0            1      0
8        1    1            0      1
10       0    1            0      0
11       1    0            1      1
12       1    1            1      0
13       1    0            1      0
14       0    0            1      1
15       0    0            1      1
16       1    1            1      1
18       0    0            1      0
19       0    1            0      0
20       1    0            1      0
21       1    0            1      1
22       1    1            1      1
24       1    1            0      1
25       0    1            1      0
27       0    0            1      0
28       0    0            1      0
29       0    0            1      1
30       0    1            1      1
31       0    1            1      1
32       0    1            0      1
34       1    0            1      1
35       0    1            0      0
36       1    0            0      1
...    ...  ...          ...    ...
46056    0    1            0      1
46057    0    1            1      0
46058    0    1            0      1
46059    1    1            1      0
46060    1    1            1      0
46061    1    1            0      0
46062    0    0            1      0
46063    1    0            1      1
46064    1    1            0      1
46065    1    0            1      0
46066    0    0            1      0
46067    0    1            1      1
46069    1    1            1      0
46070    0    1            1      0
46071    1    0            1      0
46072    1    0            1      1
46073    1    0            1      1
46074    0    0            1      0
46075    1    0            1      1
46076    0    1            0      1
46077    1    1            1      0
46078    0    0            1      1
46080    1    0            1      1
46081    0    1            0      0
46082    1    1            1      1
46083    0    1            0      0
46084    1    1            1      0
46085    1    1            1      0
46086    1    1            1      0
46087    1    1            1      0

[41630 rows x 4 columns]

In [4]:
df_rank

w2w       t2t  w2w_samecng  InDCS
0      0.142857  0.166667     0.500000      1
1      0.111111  0.166667     0.200000      1
2      0.250000  0.250000     0.200000      1
3      0.166667  0.142857     0.500000      1
4      0.166667  0.166667     0.166667      1
5      0.125000  0.142857     0.142857      1
6      0.200000  0.250000     0.333333      0
7      0.200000  0.066667     0.333333      1
8      0.200000  0.200000     0.111111      1
9      0.125000  0.142857     0.142857      1
10     0.111111  0.142857     0.111111      0
11     0.125000  0.111111     0.125000      1
12     0.111111  0.111111     0.111111      0
13     0.250000  0.083333     0.500000      0
14     0.166667  0.125000     0.200000      1
15     0.142857  0.111111     0.166667      1
16     0.142857  0.142857     0.142857      1
17     0.200000  0.250000     0.250000      1
18     0.125000  0.166667     0.250000      0
19     0.125000  0.200000     0.125000      0
20     0.166667  0.125000     0.166667      0
21     0.142857  0.125000     0.142857      1
22     0.125000  0.125000     0.125000      1
23     0.250000  0.250000     0.100000      1
24     0.250000  0.250000     0.200000      1
25     0.050000  0.200000     0.200000      0
26     0.125000  0.076923     0.125000      0
27     0.050000  0.125000     0.142857      0
28     0.047619  0.100000     0.125000      0
29     0.090909  0.083333     0.111111      1
...         ...       ...          ...    ...
46058  0.111111  0.142857     0.111111      1
46059  0.125000  0.125000     0.125000      0
46060  0.111111  0.111111     0.111111      0
46061  0.500000  0.500000     0.200000      0
46062  0.076923  0.250000     0.333333      0
46063  0.250000  0.055556     0.250000      1
46064  0.200000  0.200000     0.166667      1
46065  0.166667  0.111111     0.166667      0
46066  0.090909  0.062500     0.142857      0
46067  0.100000  0.125000     0.125000      1
46068  0.100000  0.090909     0.100000      1
46069  0.100000  0.100000     0.100000      0
46070  0.250000  0.500000     0.500000      0
46071  0.500000  0.250000     0.333333      0
46072  0.500000  0.200000     0.500000      1
46073  0.500000  0.166667     0.500000      1
46074  0.200000  0.090909     0.250000      0
46075  0.200000  0.142857     0.200000      1
46076  0.142857  0.166667     0.142857      1
46077  0.142857  0.142857     0.142857      0
46078  0.200000  0.333333     0.500000      1
46079  0.250000  0.250000     0.200000      1
46080  0.250000  0.200000     0.250000      1
46081  0.166667  0.200000     0.125000      0
46082  0.166667  0.166667     0.166667      1
46083  0.125000  0.142857     0.111111      0
46084  0.125000  0.125000     0.125000      0
46085  0.111111  0.111111     0.111111      0
46086  0.500000  0.500000     0.500000      0
46087  0.500000  0.333333     0.500000      0

[46088 rows x 4 columns]

In [11]:
X = np.mat(df_bin[['w2w', 't2t', 'w2w_samecng']])
Y = np.array(df_bin['InDCS'])
kf = KFold(Y.shape[0])

lr_model = LogisticRegression(solver='lbfgs', fit_intercept=False)
for trainIndex, testIndex in kf:
    lr_model.fit(X[trainIndex, :], Y[trainIndex])
    y2 = lr_model.predict(X[testIndex, :])
    print(np.sum(y2 == Y[testIndex])/len(testIndex))
    
display(lr_model.coef_)
display(lr_model.intercept_)
display(lr_model.n_iter_)

0.580745117821
0.576853786842
0.573724416258


array([[ 0.19748053, -0.52784196,  0.14133374]])

array([ 0.])

array([7], dtype=int32)

In [12]:
X = np.mat(df_rank[['w2w', 't2t', 'w2w_samecng']])
Y = np.array(df_rank['InDCS'])
kf = KFold(Y.shape[0])

lr_model = LogisticRegression(solver='lbfgs', fit_intercept=False)
for trainIndex, testIndex in kf:
    lr_model.fit(X[trainIndex, :], Y[trainIndex])
    y2 = lr_model.predict(X[testIndex, :])
    print(np.sum(y2 == Y[testIndex])/len(testIndex))
    
display(lr_model.coef_)
display(lr_model.intercept_)
display(lr_model.n_iter_)

0.521057085205
0.502310746599
0.51471162609


array([[ 0.48586679, -0.43106278,  0.62135764]])

array([ 0.])

array([11], dtype=int32)