In [1]:
import pandas

In [2]:
import pandas as pd
import numpy as np

In [3]:
import gensim

In [4]:
import csv

In [10]:
a = [['Bishal', 'Santra']]
print(a)

[['Bishal', 'Santra']]


In [15]:
with open('test.csv', 'w') as fp:
    b = csv.writer(fp)
    b.writerows([['Whats', 'Killer'],['up']])

In [19]:
d = {}
d["Agni"] = "Stupid"
print(d.setdefault("Agni", "Good"))
print(d.setdefault("Age", "35"))
print(d)

Stupid
35
{'Agni': 'Stupid', 'Age': '35'}


In [3]:
a = np.zeros((3,3))

In [4]:
print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [6]:
a = ["Bishal", "Agbu", "Santra"]
print(a)
print(a.index("Bishal1"))

['Bishal', 'Agbu', 'Santra']


ValueError: 'Bishal1' is not in list

In [9]:
querylist = np.zeros((5,1), dtype=int)
print(querylist)
for ele in querylist:
    print(ele)

[[0]
 [0]
 [0]
 [0]
 [0]]
[0]
[0]
[0]
[0]
[0]
