In [1]:
import numpy as np
a = np.array([2,1,3,5,2,56,23,12])
def change(vec):
    vec2 = np.array(vec)
    vec2[0] = 99
    print("Inside func.: ", vec)

change(a)
print("Outside func. :", a)

Inside func.:  [ 2  1  3  5  2 56 23 12]
Outside func. : [ 2  1  3  5  2 56 23 12]


In [2]:
def RWR(prioriVec, simMat, restartP, restartNode, maxIteration):
    n = len(prioriVec)
    """
    Run Random walk with restart
    until 
    we reach steady state or max iteration steps
    """
    papMat = np.array(prioriVec)
    for i in range(maxIteration):

        prevMat = papMat

#        print('shapes',papMat.shape,va.shape,prevMat.shape)
        papMat = (restart *np.mat(ActorActor)*np.mat(papMat)) + ((1-restart)*np.mat(va))        
        diff = (np.mat(prevMat) - np.mat(papMat))
#        diff=np.transpose(diff)
        diff=np.absolute(diff)
        diffMax = np.argmax(diff)

        if  abs(diffMax) < eps and maxIteration/10 > 10:
            break
    return(papMat)

In [3]:
a = {'1': "Bishal", "2": "Agni"}
a["3"] = "Santra"
a["3"] = "Santra2"

b = []
b.append(23)
print(b)

[23]


In [4]:
import re
fs = ["123.p", "daemon.txt"]
for f in fs:
    m = re.search("^[\w]*.p$", f)
    if m != None:
        print(m.group(0)[:-2])

123


In [5]:
from utilities import printProgress, validatePickleName, pickleFixLoad
model_cbow = pickleFixLoad('extras/modelpickle10.p')
print(model_cbow)

Word2Vec(vocab=66936, size=100, alpha=0.025)


In [6]:
print(list(model_cbow.vocab.keys())[1])

saptaparRa


In [7]:
from gensim.models.word2vec import Word2Vec
text = "The French, to compensate for the lack of European manpower so far from home, initiated the strategy of training and arming native recruits ( sepoys) like European armies.  Such forces were so effective that local princes would trade large tracts of land for French trained sepoys, thus giving the French control over much of Southern India.  In response to this new threat, the British responded in kind by training their own sepoys.  By the end of the Seven Years War (1756-63), British naval superiority and sepoys under the leadership of Robert Clive had virtually ended French involvement in India.  Clive dramatically demonstrated the effectiveness of European trained sepoys at the battle of Plassey (1757) when his army of 2800 British soldiers and sepoys routed a Bengali army of 100,000 men.  Clive's victories over the Bengalis and French made the British East Indies Company a major power in India, able to install its own candidate on the Mughal throne and claim the wealthy province of Bengal for itself.  British dominance resulting from these victories had three main effects."
# text = "Bishal. Santra, Hello Agni"
text = text.lower()
text = re.split("[.?]+ *", text)
sentenceList = []
for t in text:
    sentenceList.append(re.split("[ ,]+", t))

model = Word2Vec(sentenceList, min_count = 1)



In [8]:
print(list(model.vocab.keys())[0])
print(model.similarity("major", "indies"))
print((model.similarity("the", "for")+1)/2)

so
-0.0504259815707
0.501209695401


In [4]:
a = np.mat([1/3, 2/3])
b = np.mat([
        [0.3, 0.7],
        [0.8, 0.2]
    ])

c = np.mat([0, 1])
d = 3*a*b + 4*c
d = d - c
print((b+1)/2)

[[ 0.65  0.85]
 [ 0.9   0.6 ]]


In [2]:
a = np.array([1, 3, 67, 2, 13])
b = np.array([9, 85, 97, 0, -13])
z = np.array([23, 8, 7, 10, 76])
t = np.mat([
        a,
        b,
        z
    ])
c = np.max([a, b, z], axis=0)
c2 = np.max(t, axis=0)
# print(c)
print(t)
t[[0, 2], :] = 0
print(t[1:,:])
# print(c2)

[[  1   3  67   2  13]
 [  9  85  97   0 -13]
 [ 23   8   7  10  76]]
[[  9  85  97   0 -13]
 [  0   0   0   0   0]]


In [33]:
list(range(1, 5))

[1, 2, 3, 4]

In [9]:
np.percentile(a, [30, 50,100])

array([  2.2,   3. ,  67. ])

In [10]:
a = [2, 5, [6, 4, 9]]

In [11]:
6 in a

False

In [23]:
import pandas as pd
df = pd.read_csv("../Text Segmentation/AKfinal_ans3.backup.csv", header=None, names=["index", "accuracy", "output"])
print(df["accuracy"].describe())

count    35652.000000
mean        33.745498
std         20.171268
min          0.000000
25%         18.181818
50%         33.333333
75%         50.000000
max        100.000000
Name: accuracy, dtype: float64


In [13]:
import math
def sigmoid(x):
  return 1 / (1 + math.exp(-x))

b = np.zeros((3, 3))
f = np.vectorize(sigmoid)
f(b)

array([[ 0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5]])

array([ 2,  3,  7, 13, 14, 16])